DROP TABLE IF EXISTS line_items CASCADE;
CREATE TABLE line_items (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  qty INTEGER NOT NULL,
  subtotal DECIMAL(8,2) NOT NULL
);
